TicketReservation/Models/Address.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TicketReservation.Models
{
    public class Address
    {
        public int HomeNumber { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
    }
}

TicketReservation/Models/Artist.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TicketReservation.Models
{
    public class Artist
    {
        public string ArtistName { get; set; }
        public string ConcertHours { get; set; }
        public string ArtistDescription { get; set; }
    }
}

TicketReservation/Models/ArtistPom.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TicketReservation.Models
{
    public class ArtistPom
    {
    }
}

TicketReservation/Models/Concert.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TicketReservation.Models
{
    public class Concert
    {
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public List<Artist> ArtistLists { get; set; }
        public DateTime Date { get; set; }
        public Address ConcertAddress { get; set; }
        public string Description { get; set; }
        public int NumberOfTickets { get; set; }
    }
}

TicketReservation/Models/ConcertDetails.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TicketReservation.Models
{
    public class ConcertDetails
    {
        public ConcertDetails(string concertTitle, string underTitle, string description, string imageUri)
        {
            ConcertTitle = concertTitle;
            UnderTitle = underTitle;
            Description = description;
            ImageUri = imageUri;
        }

        public string ConcertTitle { get; set; }
        public string UnderTitle { get; set; }
        public string Description { get; set; }
        public string ImageUri { get; set; }
    }
}

TicketReservation/Models/ErrorViewModel.cs
using System;

namespace TicketReservation.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TicketReservation/Models/PageConcertObject.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TicketReservation.Models
{
    public class PageConcertObject
    {
        public string Header { get; set; }
        public string HeaderDescription { get; set; }
        public string MainImageUri { get; set; }
        public string ConcertDescription { get; set; }
        public List<ArtistPom> ArtistPomList { get; set; }
        public List<TicketOption> TicketOptions { get; set; }
    }
}

TicketReservation/Models/Ticket.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TicketReservation.Models
{
    public class Ticket
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Concert ConcertObj { get; set; }
        public Address AddressObj { get; set; }
        public double TicketPrice { get; set; }
        public string PhoneNumber { get; set; }
        public string TicketCode { get; set; }
    }
}

TicketReservation/Models/TicketOption.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TicketReservation.Models
{
    public class TicketOption
    {
        public string TicketHeader { get; set; }
        public List<string> TicketDetails { get; set; }
        public string TicketPrice { get; set; }
    }
}

TicketReservation/Controllers/ConcertsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TicketReservation.Models;

namespace TicketReservation.Controllers
{
    public class ConcertsController : Controller
    {
        public IActionResult ViewAllConcerts()
        {
            List<ConcertDetails> Details = new List<ConcertDetails>();

            ConcertDetails CartiDetails = new ConcertDetails("Playboy Carti w Hali Torwar", "od 149.99 PLN", $"Jedyny taki występ w Polsce! Playboy Carti zaprezentuje po raz pierwszy na żywo utwory z wersji Deluxe kultowego albumu \"Whole Lotta Red\"!", "https://is5-ssl.mzstatic.com/image/thumb/Features115/v4/4f/6c/cf/4f6ccf13-9927-7965-d954-3178a49f8e0c/mzl.iquhwvbg.jpg/375x375cc.webp");
            ConcertDetails CoolDetails = new ConcertDetails("COOL FESTIVAL - Hala Stulecia, Wrocław", "od 299.99 PLN", "Arca, Bjork, Tyler the Creator, Amnesia Scanner, IC3PEAK, tylko w Hali Stulecia", "https://muno.pl/wp-content/uploads/2020/05/Arca-850x570.jpg");
            ConcertDetails ZenekDetails = new ConcertDetails("Zenek Martyniuk Symfonicznie", "od 99.99 PLN", "Największe hity króla disco polo w wykonaniu Narodowej Orkiestry Symfonicznej Polskiego Radia. Jedyne takie wydarzenie w stolicy Podkarpacia!", "https://i.iplsc.com/zenek-martyniuk/0009PL2T6I1M5SJB-C122-F4.jpg");

            Details.Add(CartiDetails);
            Details.Add(CoolDetails);
            Details.Add(ZenekDetails);

            ViewBag.details = Details;
            return View();
        }

        public IActionResult ZenekConcert()
        {
            PageConcertObject zenekConcertObject = new PageConcertObject();
            zenekConcertObject.Header = "Zenek Martyniuk Symfonicznie";
            zenekConcertObject.HeaderDescription = "Hala Podpromie, Rzeszów, 23/12/2021, 21:00";
            zenekConcertObject.MainImageUri = "https://ocdn.eu/pulscms-transforms/1/h25k9kpTURBXy85YzA4MGJjNmJkZDk4OGI4NTg5YjQ0ODBmMTdlNTMxNy5qcGeSlQMANs0KIM0FspMFzQNIzQH6gqEwBaExAQ";
            zenekConcertObject.ConcertDescription = "Narodowa Orkiestra Symfoniczna Polskiego Radia wykona specjalnie przygotowane aranżacje największych hitów barda muzyki disco-polo. Zenek Martyniuk - tej postaci nikomu przedstawiać nie trzeba, a twórczości króla polskiej muzyki tanecznej postarają się sprostać instrumentaliści z NOSPR. Zapraszamy serdecznie!";

            ViewBag.zenekConcert = zenekConcertObject;
            return View();
        }

        public IActionResult CartiConcert()
        {
            PageConcertObject cartiConcertObject = new PageConcertObject();
            cartiConcertObject.Header = "Playboy Carti w Hali Torwar";
            cartiConcertObject.HeaderDescription = "Hala Torwar, Warszawa, 03/07/2021, 19:30";
            cartiConcertObject.MainImageUri = "https://img.discogs.com/xx-TjXD-s5ZzcrGqNka830DN-fk=/600x846/smart/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/A-4637951-1510976555-3557.jpeg.jpg";
            cartiConcertObject.ConcertDescription = "Jeden z najwybitniejszych raperów młodego pokolenia - Playboy Carti wraz z nowym albumem \"Whole Lotta Red\" po raz pierwszy w Polsce! Gotowi na muzyczne wydarzenie roku?";

            ViewBag.cartiConcert = cartiConcertObject;
            return View();
        }

        public IActionResult CoolConcert()
        {
            PageConcertObject coolConcertObject = new PageConcertObject();
            coolConcertObject.Header = "COOL FESTIVAL - Hala Stulecia we Wrocławiu!";
            coolConcertObject.HeaderDescription = "Hala Stulecia, Wrocław, 15/09/2021, 17:00";
            coolConcertObject.MainImageUri = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Arca_Sonar_1.jpg/1200px-Arca_Sonar_1.jpg";
            coolConcertObject.ConcertDescription = "Arca, Bjork, Tyler the Creator, Amnesia Scanner, IC3PEAK, tylko w Hali Stulecia, 15 września 2021 r.!";

            ViewBag.coolConcert = coolConcertObject;
            return View();
        }
    }
}

TicketReservation/Controllers/TicketsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TicketReservation.Controllers
{
    public class TicketsController : Controller
    {
        public IActionResult OrderingTicketCarti()
        {
            ViewBag.ConcertName = "Playboy Carti w Hali Torwar";
            return View("OrderingTicket");
        }

        public IActionResult OrderingTicketCool()
        {
            ViewBag.ConcertName = "COOL FESTIVAL - Hala Stulecia we Wrocławiu!";
            return View("OrderingTicket");
        }

        public IActionResult OrderingTicketZenek()
        {
            ViewBag.ConcertName = "Zenek Martyniuk Symfonicznie";
            return View("OrderingTicket");
        }

        public IActionResult OrderingTicket()
        {
            return View();
        }
    }
}

TicketReservation/Views/Concerts/CartiConcert.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<title>Playboy Carti w hali Torwar</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    body, h1, h2, h3, h4, h5, h6 {
        font-family: "Montserrat", sans-serif
    }

    .w3-row-padding img {
        margin-bottom: 12px
    }

    .bgimg {
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
        background-image: url('@ViewBag.cartiConcert.MainImageUri');
        min-height: 100%;
    }
</style>
<body>

    <nav class="w3-sidebar w3-hide-medium w3-hide-small" style="width:40%">
        <div class="bgimg"></div>
    </nav>

    <div class="w3-main w3-padding-large" style="margin-left:40%">

        <header class="w3-container w3-center" style="padding:128px 16px" id="home">
            <h1 class="w3-jumbo"><b>@ViewBag.cartiConcert.Header</b></h1>
            <p>@ViewBag.cartiConcert.HeaderDescription</p>
        </header>

        <div class="w3-content w3-justify w3-text-grey w3-padding-32" id="about">
            <h2>Opis koncertu</h2>
            <hr class="w3-opacity">
            <p>
                @ViewBag.cartiConcert.ConcertDescription
            </p>

            <h3 class="w3-padding-24">Artyści</h3>
            <img src="https://img.discogs.com/xx-TjXD-s5ZzcrGqNka830DN-fk=/600x846/smart/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/A-4637951-1510976555-3557.jpeg.jpg" alt="Avatar" class="w3-left w3-circle w3-margin-right" style="width:80px">
            <p><span class="w3-large w3-text-black w3-margin-right">Playboy Carti</span> 19:30 - 20:45</p>
            <p>Amerykański raper, autor takich hitów jak "Stop Breathing", "R.I.P.", "Rockstar Made"</p><br>

            <h3 class="w3-padding-16">Opcje biletów</h3>
            <div class="w3-row-padding" style="margin:0 -16px">
                <div class="w3-half w3-margin-bottom">
                    <ul class="w3-ul w3-center w3-card w3-hover-shadow">
                        <li class="w3-dark-grey w3-xlarge w3-padding-32">Sektor A (miejsca stojące)</li>
                        <li class="w3-padding-16">miejsca stojące przy scenie, najlepsza widoczność i odbiór dźwięku</li>
                        <li class="w3-padding-16">liczba miejsc: 500</li>
                        <li class="w3-padding-16">
                            <h2>199.99 PLN</h2>
                        </li>
                        <li class="w3-light-grey w3-padding-24">
                            <p><a href="@Url.Action("OrderingTicketCarti", "Tickets")">Zamów bilet</a></p>
                        </li>
                    </ul>
                </div>

                <div class="w3-half">
                    <ul class="w3-ul w3-center w3-card w3-hover-shadow">
                        <li class="w3-black w3-xlarge w3-padding-32">Sektor B (miejsca siedzące)</li>
                        <li class="w3-padding-16">miejsca siedzące na piętrze w większej odległości od sceny, słabsza widoczność niż w sektorze A</li>
                        <li class="w3-padding-16">liczba miejsc: 50</li>
                        <li class="w3-padding-16">
                            <h2>149.99 PLN</h2>
                        </li>
                        <li class="w3-light-grey w3-padding-24">
                            <p><a href="@Url.Action("OrderingTicketCarti", "Tickets")">Zamów bilet</a></p>
                        </li>
                    </ul>
                </div>
            </div>

        </div>

        <div class="w3-padding-32 w3-content w3-text-grey" id="contact" style="margin-bottom:64px">
            <h2>Kontakt w sprawie koncertu</h2>
            <hr class="w3-opacity">

            <div class="w3-section">
                <p><i class="fa fa-map-marker fa-fw w3-xxlarge w3-margin-right"></i> ul. Mieszka I 14, 67-320 Małomice</p>
                <p><i class="fa fa-phone fa-fw w3-xxlarge w3-margin-right"></i> 881 052 365</p>
                <p><i class="fa fa-envelope fa-fw w3-xxlarge w3-margin-right"> </i> przemyslawcukierski@o2.pl</p>
            </div>
        </div>

</body>
</html>

TicketReservation/Views/Concerts/CoolConcert.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
<title>Playboy Carti w hali Torwar</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    body, h1, h2, h3, h4, h5, h6 {
        font-family: "Montserrat", sans-serif
    }

    .w3-row-padding img {
        margin-bottom: 12px
    }

    .bgimg {
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
        background-image: url('https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Arca_Sonar_1.jpg/1200px-Arca_Sonar_1.jpg');
        min-height: 100%;
    }
</style>
</head>
<body>

    <nav class="w3-sidebar w3-hide-medium w3-hide-small" style="width:40%">
        <div class="bgimg"></div>
    </nav>

    <div class="w3-main w3-padding-large" style="margin-left:40%">

        <header class="w3-container w3-center" style="padding:128px 16px" id="home">
            <h1 class="w3-jumbo"><b>COOL FESTIVAL - Hala Stulecia we Wrocławiu!</b></h1>
            <p>Hala Stulecia, Wrocław, 15/09/2021, 17:00</p>
        </header>

        <div class="w3-content w3-justify w3-text-grey w3-padding-32" id="about">
            <h2>Opis koncertu</h2>
            <hr class="w3-opacity">
            <p>
                Arca, Bjork, Tyler the Creator, Amnesia Scanner, IC3PEAK, tylko w Hali Stulecia, 15 września 2021 r.!
            </p>

            <h3 class="w3-padding-24">Artyści</h3>
            <img src="https://the-talks.com/wp-content/uploads/2017/11/Bjork-01-1460x760.jpg" alt="Avatar" class="w3-left w3-circle w3-margin-right" style="width:80px">
            <p><span class="w3-large w3-text-black w3-margin-right">Bjork</span> 17:00 - 18:30</p>
            <p>Legendarna islandzka wokalistka, od 30 lat nieprzerwanie szokuje i inspiruje kolejne pokolenia fanów muzyki</p><br>

            <img src="https://static.wikia.nocookie.net/naszaeurowizja/images/7/78/Tumblr_odtkl4UTEW1slpn1co1_1280.jpg/revision/latest/scale-to-width-down/300?cb=20200904230610&path-prefix=pl" alt="Avatar" class="w3-left w3-circle w3-margin-right" style="width:80px">
            <p><span class="w3-large w3-text-black w3-margin-right">IC3PEAK</span> 18:45 - 20:15</p>
            <p>Duet muzyki elektronicznej prosto z Rosji - zapraszamy na elektryzującą podróż na Wschód!</p><br>

            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Arca_Sonar_1.jpg/1200px-Arca_Sonar_1.jpg" alt="Avatar" class="w3-left w3-circle w3-margin-right" style="width:80px">
            <p><span class="w3-large w3-text-black w3-margin-right">Arca</span> 20:30 - 22:00</p>
            <p>Wenezuelska twórczyni muzyki elektronicznej, autorka m.in. albumów "Arca" i "Kick I" po raz pierwszy w Polsce!</p><br>

            <img src="https://scontent-frt3-2.xx.fbcdn.net/v/t1.6435-9/200918005_340253644126980_6018152474060479353_n.jpg?_nc_cat=1&ccb=1-4&_nc_sid=09cbfe&_nc_ohc=okgthdfXqw4AX8fzRTc&_nc_ht=scontent-frt3-2.xx&oh=9592a0d61c93c75b6988601aa59d3ac6&oe=6134790C" alt="Avatar" class="w3-left w3-circle w3-margin-right" style="width:80px">
            <p><span class="w3-large w3-text-black w3-margin-right">Tyler the Creator</span> 22:15 - 23:45</p>
            <p>Tego rapera nikomu nie trzeba przedstawiać - laureat nagrody Grammy za album "IGOR" zabierze Was w sentymentalną podróż ze swoim nowym albumem</p><br><br />

            <img src="https://www.nowamuzyka.pl/wp-content/uploads/2018/09/xa2258833945_10-1024x1024.jpg.pagespeed.ic.6vEbBteenx.webp" alt="Avatar" class="w3-left w3-circle w3-margin-right" style="width:80px">
            <p><span class="w3-large w3-text-black w3-margin-right">Amnesia Scanner</span> 00:00 - 01:30</p>
            <p>Na koniec koncertu awangardowy zespół prosto z Finlandii - Amnesia Scanner czyli jedna z najbardziej zaskakujących formacji w muzyce elektronicznej ostatnich lat!</p><br>
            
            <h3 class="w3-padding-16">Opcje biletów</h3>
            <div class="w3-row-padding" style="margin:0 -16px">
                <div class="w3-half w3-margin-bottom">
                    <ul class="w3-ul w3-center w3-card w3-hover-shadow">
                        <li class="w3-dark-grey w3-xlarge w3-padding-32">Sektor A</li>
                        <li class="w3-padding-16">miejsca przy scenie</li>
                        <li class="w3-padding-16">liczba miejsc: 200</li>
                        <li class="w3-padding-16">
                            <h2>399.99 PLN</h2>
                        </li>
                        <li class="w3-light-grey w3-padding-24">
                            <p><a href="@Url.Action("OrderingTicketCool", "Tickets")">Zamów bilet</a></p>
                        </li>
                    </ul>
                </div>

                <div class="w3-half">
                    <ul class="w3-ul w3-center w3-card w3-hover-shadow">
                        <li class="w3-black w3-xlarge w3-padding-32">Sektor B</li>
                        <li class="w3-padding-16">miejsca siedzące w odległości 20-30 metrów od sceny</li>
                        <li class="w3-padding-16">liczba miejsc: 50</li>
                        <li class="w3-padding-16">
                            <h2>299.99 PLN</h2>
                        </li>
                        <li class="w3-light-grey w3-padding-24">
                            <p><a href="@Url.Action("OrderingTicketCool", "Tickets")">Zamów bilet</a></p>
                        </li>
                    </ul>
                </div>

                <div class="w3-half">
                    <ul class="w3-ul w3-center w3-card w3-hover-shadow">
                        <li class="w3-black w3-xlarge w3-padding-32">Sektor C</li>
                        <li class="w3-padding-16">miejsca siedzące w odległości 40-50 metrów od sceny</li>
                        <li class="w3-padding-16">liczba miejsc: 150</li>
                        <li class="w3-padding-16">
                            <h2>249.99 PLN</h2>
                        </li>
                        <li class="w3-light-grey w3-padding-24">
                            <button class="w3-button w3-white w3-padding-large w3-hover-black">Zamów bilet</button>
                        </li>
                    </ul>
                </div>
            </div>

        </div>

        <div class="w3-padding-32 w3-content w3-text-grey" id="contact" style="margin-bottom:64px">
            <h2>Kontakt w sprawie koncertu</h2>
            <hr class="w3-opacity">

            <div class="w3-section">
                <p><i class="fa fa-map-marker fa-fw w3-xxlarge w3-margin-right"></i> ul. Mieszka I 14, 67-320 Małomice</p>
                <p><i class="fa fa-phone fa-fw w3-xxlarge w3-margin-right"></i> 881 052 365</p>
                <p><i class="fa fa-envelope fa-fw w3-xxlarge w3-margin-right"> </i> przemyslawcukierski@o2.pl</p>
            </div>
        </div>

</body>
</html>

TicketReservation/Views/Concerts/ViewAllConcerts.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <style>
        .card {
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            max-width: 300px;
            margin: auto;
            text-align: center;
            font-family: arial;
        }

        .price {
            color: grey;
            font-size: 22px;
        }

        .card button {
            border: none;
            outline: 0;
            padding: 12px;
            color: white;
            background-color: #000;
            text-align: center;
            cursor: pointer;
            width: 100%;
            font-size: 18px;
        }

        .myButtonClass {
            border: none;
            outline: 0;
            padding: 12px;
            color: white;
            background-color: #000;
            text-align: center;
            cursor: pointer;
            width: 100%;
            font-size: 18px;
        }

        .myButtonClass:hover{
            opacity: 0.7;
        }

            .card button:hover {
                opacity: 0.7;
            }
    </style>
</head>
<body>

    <div class="card">
        <img src="@ViewBag.details[0].ImageUri" alt="Denim Jeans" style="width:100%">
        <h1>@ViewBag.details[0].ConcertTitle</h1>
        <p class="price">@ViewBag.details[0].UnderTitle</p>
        <p>@ViewBag.details[0].Description</p>
        <p><a href="@Url.Action("CartiConcert", "Concerts")" class="myButtonClass">Zamów bilet</a></p>
    </div>
    <br />

    <div class="card">
        <img src="@ViewBag.details[1].ImageUri" alt="Denim Jeans" style="width:100%">
        <h1>@ViewBag.details[1].ConcertTitle</h1>
        <p class="price">@ViewBag.details[1].UnderTitle</p>
        <p>@ViewBag.details[1].Description</p>
        <p><a href="@Url.Action("CoolConcert", "Concerts")" class="myButtonClass">Zamów bilet</a></p>
    </div>
    <br />

    <div class="card">
        <img src="@ViewBag.details[2].ImageUri" alt="Denim Jeans" style="width:100%">
        <h1>@ViewBag.details[2].ConcertTitle</h1>
        <p class="price">@ViewBag.details[2].UnderTitle</p>
        <p>@ViewBag.details[2].Description</p>
        <p><a href="@Url.Action("ZenekConcert", "Concerts")" class="myButtonClass">Zamów bilet</a></p>
    </div>
    <br />

</body>
</html>

TicketReservation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TicketReservation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TicketReservation</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - TicketReservation - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>